name: Build, Test, and Deploy to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-test-01   # Change this to your app service name
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/springboot-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build and Test
      run: ./gradlew build
      env:
        MONGODB_USERNAME: ${{ secrets.TEST_MONGODB_USERNAME }}
        MONGODB_PASSWORD: ${{ secrets.TEST_MONGODB_PASSWORD }}
        MONGODB_DATABASE: user_management_test_db

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/*.jar
        retention-days: 5

  dockerize-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} .
        docker tag ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_IMAGE }}:latest
        docker push ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.DOCKER_IMAGE }}:latest

  deploy-to-azure:
    needs: dockerize-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

    - name: Azure logout
      run: |
        az logout